server:
  port: 80
  
application:
  security: 
    social:
      qq:
        app-id: 
        app-secret: 
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
    code:
      image:
        url: /authentication/form
      sms:
        url: /authentication/mobile

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/security_demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456        